version: "3"
services:
  client:
    build:
      context: ./test-app/
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
  
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "7000:3000"
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: