version: "3"
services:
  client:
    build:
      context: ./test-app/
      dockerfile: Dockerfile.prod
    command: npm run start
    # ports:
    #   - "3000:3000"
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: 
    - ./.env
    command: npm run start
    # ports:
    #   - "7000:3000"
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis

volumes:
  mongo-db: