version: "3"
services:
  # client:
  #   build:
  #     context: ./test-app
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./test-app:/app
  #     - /app/node_modules
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - redis-net
    command: npm run dev
  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    #restart: always
    networks:
      - redis-net
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]

networks:
  redis-net:

volumes:
  mongo-db:
