version: "3"
services:
  client:
    build:
      context: ./test-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./test-app:/app
      - /app/node_modules
  
  nginx:
    image: nginx
    ports:
      - "7000:80"
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "7000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: 
      - ./.env
    command: npm run dev
  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis

volumes:
  mongo-db:
